title: Notes from Carmen
description: Helping people reflect deeply, move past internal blockers, and grow into more intentional versions of themselves, through psychology, creativity, and experiential workshops.
theme: jekyll-theme-cayman
